"""init

Revision ID: 04b7766a0518
Revises: 
Create Date: 2026-05-10 02:34:31.285214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b7766a0518'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couple_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invite_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_token')
    )
    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_currency', 'to_currency', 'date', name='uq_fx_per_day')
    )
    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fx_rates_date'), ['date'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('couple_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['couple_group_id'], ['couple_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('couple_group_id', 'name', name='uq_category_per_group')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_couple_group_id'), ['couple_group_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('couple_group_id', sa.Integer(), nullable=True),
    sa.Column('preferred_currency', sa.String(length=3), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['couple_group_id'], ['couple_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_couple_group_id'), ['couple_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('condition_type', sa.String(length=20), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('threshold', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('threshold_currency', sa.String(length=3), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_owner_id'), ['owner_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('payload', sa.String(length=500), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_recipient_id'), ['recipient_id'], unique=False)

    op.create_table('spend_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('original_currency', sa.String(length=3), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spend_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spend_entries_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spend_entries_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_spend_entries_user_id'), ['user_id'], unique=False)

    op.create_table('tripwires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setter_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('condition_type', sa.String(length=20), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('threshold', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('threshold_currency', sa.String(length=3), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['setter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tripwires', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tripwires_setter_id'), ['setter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tripwires_target_user_id'), ['target_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tripwires', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tripwires_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_tripwires_setter_id'))

    op.drop_table('tripwires')
    with op.batch_alter_table('spend_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spend_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_spend_entries_date'))
        batch_op.drop_index(batch_op.f('ix_spend_entries_category_id'))

    op.drop_table('spend_entries')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_owner_id'))

    op.drop_table('goals')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_couple_group_id'))

    op.drop_table('users')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_couple_group_id'))

    op.drop_table('categories')
    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fx_rates_date'))

    op.drop_table('fx_rates')
    op.drop_table('couple_groups')
    # ### end Alembic commands ###
